### ISSUE TITLE
taskInfo not fully populated (hostname, port)

### ISSUE THREAD

**Issue by jwestboston** [verisign/storm-graphite#10]
For some reason the taskInfo object seems to not be fully populated on/with Apache Storm 0.9.3 on CentOS 7.  Therefore, the metric name does not contain the hostname, port, and other items.

When running the word-count example from Pyleus, for example, the metrics sent to my system are like so:

    storm.word_count-1-1427311189.line-spout.__emit-count.default

with my prefix being set to "storm".

Unfortunately, this means I cannot graph metrics for each worker process :-(

What can I do to assist in troubleshooting?

**Comment by jwestboston** [comment]
Ahh!  This is because items such as srcWorkerHost are not added to the metric name in 0.1.4 :-D

This is however available in master.

I guess this is just an issue with the documentation not matching the latest [stable] release?  No doubt to be fixed once 0.1.5 is set as stable/released...

**Comment by miguno** [comment]
You can simply build+package 0.1.5-SNAPSHOT if you need these semantics already right now.

**Comment by jwestboston** [comment]
@miguno Exactly what I did.  Workin' great -- thanks.

On a side note, it seems that metrics emitted from storm-graphite do not match metrics presented in the Storm UI.  Is this due to the Storm UI not being accurate due to only taking samples?

**Comment by miguno** [comment]
Happy to hear it works for you now!

And yes, the metrics in Storm’s UI are sampled.  See `Config.TOPOLOGY_STATS_SAMPLE_RATE` as described at http://www.michael-noll.com/blog/2013/11/06/sending-metrics-from-storm-to-graphite/.

**Comment by jwestboston** [comment]
@miguno Thanks!
