### ISSUE TITLE
Missing metrics 

### ISSUE THREAD

**Issue by mathieuboniface** [verisign/storm-graphite#18]
We've just installed storm-graphite. Some of the `storm-ui` metrics are well exported to our db, but we do not find any metrics related to latency or executed tuple count.

Here are the metrics we find for _1 topology node / 1 worker / 1 task_.
```
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.__metrics
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.__system
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.capacity
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.default
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.population
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.read_pos
storm.metrics.TOPOLOGY_NAME-MySpout.worker1.6700.3.write_pos
```

Do you have any clue to have the missing metrics like `__execute-count` or `__execute-latency` getting exported ?

**Comment by binhnv** [comment]
I am seeing the same as I reported in #15. I think it is a bug in the code that does not put data point's name in the metric prefix calculation. This bug was introduced in the commit for KafkaAdapter
6660a5b7d5c9ce17660ed72e5aac011d0c42be17

**Comment by KevinJMao** [comment]
@binhnv It looks like you're correct, the data point's name is being left out of the output metric path. I'll add it back in and tag a new build.

**Comment by mathieuboniface** [comment]
I've just redeployed the jar, and it works as expected now.

Thanks for this quick fix.
