### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alecinvan** [verisign/storm-graphite#4]
Hi, 

I just can't build by having such errors:
```
:copyCoberturaDatafile SKIPPED
:compileTestJava
Note: /home/stuser/stormprj/storm-graphite/src/test/java/com/verisign/storm/metrics/GraphiteMetricsConsumerTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processTestResources UP-TO-DATE
:testClasses
:test

com.verisign.storm.metrics.graphite.GraphiteAdapterTest.connectClientToGraphiteServer FAILED
    java.net.BindException at GraphiteAdapterTest.java:53

39 tests completed, 1 failed, 38 skipped
:test FAILED
:generateCoberturaReport SKIPPED
:performCoverageCheck SKIPPED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/stuser/stormprj/storm-graphite/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.698 secs
```

any ideas?

AL

**Comment by alecinvan** [comment]
Btw, my os is ubuntu, seems I am having trouble to get storm-graphite working my box.

**Comment by KevinJMao** [comment]
@alecinvan it may be that port 2003 is being used by another process. Could you run `netstat -ln` and ensure that port isn't being bound during the tests?

**Comment by alecinvan** [comment]
Awesome, carbon-cache take 2003, I rebuild it, and worked. Next question is, do I have to package it to RPM? My OS is ubuntu, I assume all of your release are in centos, that are not working perfectly on my boxes. Do you have an ubuntu version, and not just tool, and other tools you team released. 

thanks

**Comment by KevinJMao** [comment]
I'll take a look at adding .DEB packaging support.

#5

**Comment by alecinvan** [comment]
Thanks a lot.

**Comment by miguno** [comment]
@alecinvan If I understand correctly your question has been answered, and we track the new feature request for .deb packages in a separate ticket.  Hence I'm closing this ticket.
