### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by lexicalunit** [verisign/storm-graphite#8]
The documentation mentions support for Java 6 and 7. We are considering moving to Java 8. Do you expect storm-graphite will work with Java 8 or is it known not to work with it?

**Comment by miguno** [comment]
We are not using Java 8 so I can't tell.  That being said I don't see a reason why it should not work.  Feel free to give it a go and report back.

**Comment by lexicalunit** [comment]
Right on, that's kinda what I had assumed was the case. We're going to try it out with storm v0.10.0 and Java 8. Definitely will report back on success/failure.
